spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music_graph
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  access:
    secret_key: "Y29udHJhc2XDsWEgZmFjaGVyaXRhY29udHJhc2XDsWEgZmFjaGVyaXRhY29udHJhc2XDsWEgZmFjaGVyaXRh"
    expiration: 3600000        # 1 hora
  refresh:
    expiration: 604800000     # 7 dias

cookie:
  secure: false